// Generated by CoffeeScript 1.6.2
define(['./stylus'], function() {
  return {
    load: function(name, req, onload, config) {
      return $.get("" + name + ".styl", function(data) {
        data = data.replace(/\t/g, "  ").replace(/^\s+/, "").replace(/\s+$/, "");
        return stylus(data).render(function(err, str) {
          if (err) {
            throw err;
          }
          $('head').append("<style>" + str + "</style>");
          return onload(true);
        });
      });
    }
  };
});
